functionnames = c("GetAllModelIDs", "NumberofCompartmentsInEachModel", "SummariseCompartmentData","NumberofSpeciesInEachModel", "NumberofReactionsInEachModel", "NumberofGlobalParametersInEachModel", "NumberofLocalParametersInEachModel", "GetParameters", "ProportionOfUnknownParameters", "ProportionOfUnknownParametersForallModels", "ProportionOfUnknownSpecies", "ProportionOfUnknownSpeciesForallModels")
source("functions2.R")
IDs = GetAllModelIDs(Models)
comparts_summary = SummariseCompartmentData(NumberofCompartmentsInEachModel(Models))
specs = NumberofSpeciesInEachModel(Models)
reacts = NumberofReactionsInEachModel(Models)
globalparams = NumberofGlobalParametersInEachModel(Models)
localparams = NumberofLocalParametersInEachModel(Models)
rm(list=functionnames)
rm(list=c("functionnames"))