functionnames <- c("AverageNumberOfConnections", "ConvertDateStringsToYears", "CummulativeNumberOfModelsInEachYear", "CummulativeNumberOfSpeciesInEachYear", "DataFrameOfsboTermsinAllModels", "DataFrameOfsboTermsInaModel", "FindAllYears", "FrequencyOfsboTermsInaModel", "GetAllConnections", "GetAllConnectionsInAModel", "GetAllSpeciesFromAYear", "GetModelsboTerms", "GetSpeciesIDsForaModel", "GetStartDateStrings", "GetUniqueSpecies", "IdentifyAllModelsInAnyGivenYear", "OrderSpeciesIDs", "ReactionConnections", "SortOutAllConnections")
source("functions3.R")
startdatestrings <- GetStartDateStrings(Models)
startyears <- ConvertDateStringsToYears(startdatestrings)
allyears <- FindAllYears(startyears)
cummulativenumberofmodels <- CummulativeNumberOfModelsInEachYear(startyears)
cummulativenumberofspecies <- CummulativeNumberOfSpeciesInEachYear(Models, startyears)
rm(list=functionnames)
rm(functionnames)