functionnames = c("GetAllModelIDs", "NumberofCompartmentsInEachModel", "SummariseCompartmentData","NumberofSpeciesInEachModel", "NumberofReactionsInEachModel", "NumberofGlobalParametersInEachModel", "NumberofLocalParametersInEachModel", "GetParameters", "ProportionOfUnknownParameters", "ProportionOfUnknownParametersForallModels", "ProportionOfUnknownSpecies", "ProportionOfUnknownSpeciesForallModels")
source("functions2.R")
IDs = GetAllModelIDs(Models)
comparts = NumberofCompartmentsInEachModel(Models)
specs = NumberofSpeciesInEachModel(Models)
reacts = NumberofReactionsInEachModel(Models)
globalparams = NumberofGlobalParametersInEachModel(Models)
localparams = NumberofLocalParametersInEachModel(Models)
localparameterspresent = localparams != 0
unknowparmetersproportions = ProportionOfUnknownParametersForallModels(Models)
unknowspeciesproportions = ProportionOfUnknownSpeciesForallModels(Models)
df = data.frame(IDs, comparts, specs, reacts, globalparams, localparameterspresent, localparams, unknowspeciesproportions, unknowparmetersproportions, stringsAsFactors = FALSE)
colnames(df) = c("Model ID", "Compartments", "Species", "Reactions", "GlobalParameters", "LocalParametersPresent?", "Local Parameters", "UnknownSpecies", "UnknownParameters")
rm(list=functionnames)
rm(functionnames)