functionnames = c("GetAllModelIDs", "NumberofCompartmentsInEachModel", "SummariseCompartmentData","NumberofSpeciesInEachModel", "NumberofReactionsInEachModel", "NumberofGlobalParametersInEachModel", "NumberofLocalParametersInEachModel", "GetParameters", "ProportionOfUnknownParameters", "ProportionOfUnknownParametersForallModels", "ProportionOfUnknownSpecies", "ProportionOfUnknownSpeciesForallModels")
source("functions2.R")
IDs = GetAllModelIDs(Models)
comparts = NumberofCompartmentsInEachModel(Models)
specs = NumberofSpeciesInEachModel(Models)
reacts = NumberofReactionsInEachModel(Models)
globalparams = NumberofGlobalParametersInEachModel(Models)
localparams = NumberofLocalParametersInEachModel(Models)
localparameterspresent = localparams != 0
unknowparmetersproportions = ProportionOfUnknownParametersForallModels(Models)
unknowspeciesproportions = ProportionOfUnknownSpeciesForallModels(Models)
df = data.frame(IDs ,comparts ,specs ,reacts ,globalparams ,localparameterspresent, localparams ,unknowspeciesproportions, unknowparmetersproportions,stringsAsFactors = FALSE)
colnames(df) = c("Model ID", "Number of \nCompartments", "Number of \nSepcies", "Number of \nReactions", "Number of \nGlobal Parameters", "Local Parameters \nPresent?", "Number of \nLocal Parameters", "Proportion of Species \nwith Unknown Inital \nAmount/Concentration", "Proportion of Parameters \nwith Unknown Initial Values")
rm(list=functionnames)
rm(functionnames)